Vereinsverwaltung/Models/ViewModels/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Vereinsverwaltung.Models
{
    public class Login
    {
        [Required]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Bitte geben sie eine email an")]
        public String Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public String Password { get; set; }
    }
}

Vereinsverwaltung/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vereinsverwaltung.Models;
using Vereinsverwaltung.Services;
using System.Web.Security;
using Vereinsverwaltung.Repositories;
using Vereinsverwaltung.ActionFilter;

namespace Vereinsverwaltung.Controllers
{
    [GlobalAuthorizeAttribute]
    public class ClubController : Controller
    {
        private ClubContext db = new ClubContext();

        private AuthentificationService auth = new AuthentificationService();
        private RegisterService reg = new RegisterService();
        private IClubRepository clubRepository = new ClubRepository();
        private IUserRepository userRepository = new UserRepository();


        [RoleAuthorizeAttribute(Redirect = "Club/Home")]
        public ActionResult Index()
        {
            return View(this.clubRepository.GetClubByID((int)ViewData["ClubId"]));
        }

        public ActionResult Home()
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("index");
            }
            else
            {
                ViewBag.Message = "Willkommen Auf der Vereinsverwaltung App";

                return View();
            }
            
        }

        //
        // GET: /Club/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Club/Create

        [HttpPost]
        public ActionResult Create(Register register)
        {
            if (ModelState.IsValid)
            {
                User user = reg.CreateClubUser(register, 1);
                //Session.Add("clubID", user.ClubID);
                FormsAuthentication.SetAuthCookie(register.Email, false);
                return RedirectToAction("Index", "User");  
            }

            return View();
        }
        
        //
        // GET: /Club/Edit/

        [RoleAuthorizeAttribute(Redirect = "Club/Home", Role = new string[] { "Leiter" })]
        public ActionResult Edit()
        {
            Club club = this.clubRepository.GetClubByID((int)ViewData["ClubId"]);
            return View(club);

        }

        //
        // POST: /Club/Edit/

        [HttpPost]
        [RoleAuthorizeAttribute(Redirect = "Club/Home", Role = new string[] { "Leiter" })]
        [ClubAuthorizeAttribute]
        public ActionResult Edit(Club club)
        {

            if (ModelState.IsValid)
            {
                this.clubRepository.UpdateClub(club);
                this.clubRepository.Save();
                return RedirectToAction("Index");
            }
            return View(club);

        }
    }
}

Vereinsverwaltung/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vereinsverwaltung.Models;
using Vereinsverwaltung.Repositories;
using Vereinsverwaltung.Services;
using System.Diagnostics;
using Vereinsverwaltung.ActionFilter;

namespace Vereinsverwaltung.Controllers
{
    [GlobalAuthorizeAttribute]
    public class GroupController : Controller
    {
        private ClubContext db = new ClubContext();
        private AuthentificationService auth = new AuthentificationService();

        private IUserRepository userRepository = new UserRepository();
        private IGroupRepository groupRepository = new GroupRepository();

        //
        // GET: /Group/

        [RoleAuthorizeAttribute]
        public ActionResult Index()
        {
            int clubID = (int)ViewData["ClubId"];
            return View(this.groupRepository.getClubGroups(clubID));
        }

        //
        // GET: /Group/Details/5

        [GroupAuthorizeAttribute]
        [RoleAuthorizeAttribute]
        public ActionResult Details(int id)
        {
            Group group = this.groupRepository.GetGroupByID(id);
            return View(group);
        }

        //
        // GET: /Group/Create

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Group/Create

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        [HttpPost]
        public ActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {
                int clubID = (int)ViewData["ClubId"];

                group.ClubID = clubID;
                this.groupRepository.InsertGroup(group);
                this.groupRepository.Save();
                return RedirectToAction("Edit", new { id = group.GroupID });
            }

            return View(group);
        }
        
        //
        // GET: /Group/Edit/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Edit(int id)
        {

            Group group = this.groupRepository.GetGroupByID(id);
            if (group == null) return RedirectToAction("index");
            IEnumerable<User> clubUsers = this.userRepository.getClubUsers(group.ClubID);
            List<User> availableGroupUsers = new List<User>();

            foreach (var clubUser in clubUsers)
            {
                Boolean isInside = false;
                foreach (var groupUser in group.Users)
                {
                    if (clubUser.UserID == groupUser.UserID)
                    {
                        isInside = true;
                    }
                }
                if (!isInside)
                {
                    availableGroupUsers.Add(clubUser);
                }
            }
            ViewBag.ClubUsers = availableGroupUsers;
            return View(group);

        }

        //
        // POST: /Group/Edit/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        [HttpPost]
        public ActionResult Edit(Group group)
        {
            if (ModelState.IsValid)
            {
                this.groupRepository.UpdateGroup(group);
                this.groupRepository.Save();
                return RedirectToAction("Index");

            }
            return View(group);
        }

        //
        // GET: /Group/Delete/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Delete(int id)
        {
            Group group = this.groupRepository.GetGroupByID(id);
            return View(group);
        }

        //
        // POST: /Group/Delete/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            this.groupRepository.DeleteGroup(id);
            this.groupRepository.Save();

            return RedirectToAction("Index");
        }

        //
        // GET: /Group/5/AddUser/1

        public ActionResult AddUser(int groupid, int userid)
        {
            this.groupRepository.InsertUser(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Group/5/RemoveUser/1

        public ActionResult RemoveUser(int groupid, int userid)
        {
            this.groupRepository.RemoveLeader(groupid, userid);
            this.groupRepository.Save();
            this.groupRepository.RemoveUser(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Group/5/AddLeader/1

        public ActionResult AddLeader(int groupid, int userid)
        {
            this.groupRepository.AddLeader(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Group/5/RemoveLeader/1

        public ActionResult RemoveLeader(int groupid, int userid)
        {
            this.groupRepository.RemoveLeader(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public int getClubID()
        {
            if (Session["clubID"] != null)
            {
                return (int)Session["clubID"];
            }
            else
            {
                int clubID = auth.getClubIdByEmail(System.Web.HttpContext.Current.User.Identity.Name);
                Session.Add("clubID", clubID);
                return clubID;
            }
        }
    }
}

Vereinsverwaltung/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/visualsearch-datauri.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/visualsearch.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <!--[if IE]>
    <link href="@Url.Content("~/Content/jquery.ui.1.8.16.ie.css")" rel="stylesheet" type="text/css" />
    <![endif]-->

    
    <!--scripts-->
    <script src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/underscore.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/backbone.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/date.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-dropdown.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-alerts.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-tabs.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/visualsearch.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/icanhaz.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.address-1.4.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/site.js")" type="text/javascript"></script>
    

    <script id="usertemplate" type="text/html">
      <li class="well">
        <h5 class="name"><a href="/User/Details/{{ id }}">{{ firstname }} {{ lastname }}</a></h5>
        <p><strong>Email:</strong> {{ email }} <strong>Geburtstag:</strong> {{ birthdate }} <strong>Role:</strong> {{ role }}</p>
      </li>
    </script>
</head>

<body>
    
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Vereinsverwaltung</a>

          <ul class="nav">
            <li>@Html.ActionLink("Home", "Index", "Club")</li>
            <li>@Html.ActionLink("Gruppen", "Index", "Group")</li>
            <li>@Html.ActionLink("Mitglieder", "Search", "User")</li>
          </ul>

          @Html.Partial("_Login")
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <div class="page-header">
          <h1>@ViewBag.title</h1>
        </div>
        <div class="row">
          <div class="span14">
            @RenderBody()
          </div>
        </div>
      </div>

      <footer>
        <p>&copy; Vereinsverwaltung 2012</p>
      </footer>

    </div> <!-- /container -->

</body>
</html>

Vereinsverwaltung/Views/Shared/_Login.cshtml
@{
    ViewBag.Title = "Login";
    Vereinsverwaltung.Models.Login login = new Vereinsverwaltung.Models.Login();
}

@{
    if (Request.IsAuthenticated)
    {
        <ul class="nav secondary-nav">
            <li class="dropdown" data-dropdown="dropdown">
                <a href="#" class="dropdown-toggle">Mein Account</a>
                <ul class="dropdown-menu">
                <li><a href="#">@Html.ActionLink("Profile", "Edit", "User", new { id = (int)ViewData["UserId"] }, null)</a></li>
                @if (ViewData["GroupLeader"] == "yes" || (int)ViewData["Role"] == 1)
                {
                    <li><a href="#">@Html.ActionLink("Neues Mitglied", "Create", "User", null)</a></li>
                }  
                <li class="divider"></li>
                <li><a href="#">@Html.ActionLink("Logout", "Logout", "Account")</a></li>
                </ul>
            </li>
        </ul>    
    }
    else
    {
        using (Html.BeginForm("Login", "Account", FormMethod.Post, new { @class = "pull-right" }))
        {
            
            @Html.TextBoxFor(model => login.Email, new { @class = "input-small", @placeholder = "Email" })
            @Html.PasswordFor(model => login.Password, new { @class = "input-small", @placeholder = "Password" })
            <button class="btn" type="submit">Login</button>
        }

    }
}