Vereinsverwaltung/Models/Checkout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Vereinsverwaltung.Models
{
    public class Checkout
    {
        public int CheckoutID { get; set; }

        public int ClubID { get; set; }

        public int GroupID { get; set; }
        public virtual Group Group { get; set; }

        [Required(ErrorMessage = "Bitte geben Sie einen Betrag an")]
        [DisplayName("Betrag")]
        public Double Amount { get; set; }

        [Required]
        [DisplayName("Fälligkeitsdatum")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime MaturityDate { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

Vereinsverwaltung/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vereinsverwaltung.Models;
using Vereinsverwaltung.Repositories;
using Vereinsverwaltung.Services;
using System.Collections;
using Vereinsverwaltung.ActionFilter;

namespace Vereinsverwaltung.Controllers
{
    [GlobalAuthorizeAttribute]
    [RoleAuthorizeAttribute(Role = new string[] { "Leiter", "Kassier" })]
    public class CheckoutController : Controller
    {
        private ClubContext db = new ClubContext();
        private AuthentificationService auth = new AuthentificationService();

        private IUserRepository userRepository = new UserRepository();
        private IGroupRepository groupRepository = new GroupRepository();
        private ICheckoutRepository checkoutRepository = new CheckoutRepository();
        private ITransactionRepository transactionRepository = new TransactionRepository();

        //
        // GET: /Checkout/

        public ActionResult Index()
        {

            int clubID = (int)ViewData["ClubId"];
            return View(this.checkoutRepository.getClubCheckouts(clubID));

        }

        //
        // GET: /Checkout/Create

        public ActionResult Create()
        {
            List<Group> Groups = this.groupRepository.getClubGroups((int)ViewData["ClubId"]).ToList();
            ViewBag.GroupID = new SelectList(Groups, "GroupID", "Name");
            return View();   
        } 

        //
        // POST: /Checkout/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Checkout/Edit/5
 
        public ActionResult Edit(int id)
        {
            /*
        Checkout checkout = this.checkoutRepository.GetCheckoutByID(id);
        Hashtable clubUsersOpen = this.transactionRepository.GetOpenUser(id);
        ViewBag.clubUsersOpen = clubUsersOpen;
          
        foreach (var g in clubUsersOpen.Keys)
        {
            foreach (var u in (ArrayList)clubUsersOpen[g])
            {
                Boolean isInside = false;
                foreach (var trans in checkout.Transactions)
                {
                    if (clubUser.UserID == trans.User.UserID)
                    {
                        isInside = true;
                    }
                }
                if (!isInside)
                {
                    //availableGroupUsers.Add(clubUser);
                }
            }
        }*/
            //ViewBag.ClubUsers = availableGroupUsers;
            return View();

        }

        //
        // POST: /Checkout/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Checkout/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Checkout/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Vereinsverwaltung/Views/Checkout/Create.cshtml
@model Vereinsverwaltung.Models.Checkout

@{
    ViewBag.Title = "Neuer Beitrag";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-stacked" })) 
{
    @Html.ValidationSummary(true)
    <fieldset>

        <div class="editor-label">
            @Html.LabelFor(model => model.Amount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Amount)
            @Html.ValidationMessageFor(model => model.Amount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaturityDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaturityDate)
            @Html.ValidationMessageFor(model => model.MaturityDate)
        </div>

       <div class="editor-label">
            @Html.LabelFor(model => model.GroupID, "Gruppe")
        </div>
        <div class="editor-field">
            @Html.DropDownList("GroupID", String.Empty)
            @Html.ValidationMessageFor(model => model.GroupID)
        </div>

        <div class="actions">
            <input type="submit" class="btn primary" value="Speichern" />
        </div>

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Vereinsverwaltung/Views/Checkout/Delete.cshtml
@model Vereinsverwaltung.Models.Group

@{
    ViewBag.Title = "Delete";
}

<div class="alert-message error fade in" data-alert="alert">
    <a class="close" href="#">×</a>
    <p><strong>Woow!</strong> Sicher das du löschen möchtest? @Html.ActionLink("Nein", "Index").</p>
</div>

<div>
    <h4>Gruppe</h4>
    <dl>
    <dt>Name</dt>
    <dd>@Html.DisplayFor(model => model.Name)</dd>
    <dt>Description</dt>
    <dd> @Html.DisplayFor(model => model.Description)</dd>
    </dl>
</div>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" class="btn danger" />
    </p>
}

Vereinsverwaltung/Views/Checkout/Edit.cshtml
@model Vereinsverwaltung.Models.Checkout

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@{
    ViewBag.Title = "Kassa";
}

<ul class="tabs" data-tabs="tabs">
    <li class="active"><a href="#group">Gruppe</a></li>
    <li><a href="#members">Mitglieder</a></li>
</ul>
<div id="my-tab-content" class="tab-content">

    @* GROUP *@
    <div class="active tab-pane" id="group">

        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-stacked" })) 
        {
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Betrag für Gruppe</legend>

                @Html.HiddenFor(model => model.CheckoutID)

                <div class="editor-label">
                    @Html.LabelFor(model => model.Group.Name)
                </div>
                <div class="editor-field">
                    @Html.DisplayFor(model => model.Group.Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Amount)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Amount)
                    @Html.ValidationMessageFor(model => model.Amount)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.MaturityDate)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.MaturityDate)
                    @Html.ValidationMessageFor(model => model.MaturityDate)
                </div>

                <div class="actions">
                    <input type="submit" class="btn primary" value="Speichern" />
                </div>
            </fieldset>
        }
    </div>

    @* MEMBERS *@
    <div class="tab-pane tab-pane-groups" id="members">

    <table>
    <tr>
        <th>
            Mitglied
        </th>
        <th>
            Betrag
        </th>
        <th>
            Buchungsdatum
        </th>
        <th />
    </tr>

@if (ViewBag.clubUsersOpen != null)
{
    foreach (Vereinsverwaltung.Models.Group g in ViewBag.clubUsersOpen.Keys)
    {
        
        <tr> Gruppe: 
            @g.Name;
        </tr>
        foreach (Vereinsverwaltung.Models.User u in (System.Collections.ArrayList)ViewBag.clubUsersOpen[g])
        {
            
    <tr>
        <td>
            @{
                @u.FirstName @u.LastName
            }
        </td>
         <td>
            
        </td>
        <td>
            
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = u.UserID}) |
            @Html.ActionLink("Details", "Details", new { id = u.UserID }) |
            @Html.ActionLink("Delete", "Delete", new { id = u.UserID })
        </td>
    </tr>
        }
    }
}

</table>

    </div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Vereinsverwaltung/Views/Checkout/Index.cshtml
@model IEnumerable<Vereinsverwaltung.Models.Checkout>

@{
    ViewBag.Title = "Kassa";
    
}



<p>
    @Html.ActionLink("Erstellen", "Create", "Checkout", new { @class = "btn primary" })
</p>
<table>
    <tr>
        <th>
            Gruppe
        </th>
        <th>
            Betrag
        </th>
        <th>
            Fälligkeitsdatum
        </th>
        <th />
    </tr>

@if (Model != null)
{
    foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Group.Name)
        </td>
         <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaturityDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.CheckoutID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.CheckoutID })
        </td>
    </tr>
    }
}

</table>