Vereinsverwaltung/Models/Group.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Vereinsverwaltung.Models
{
    public class Group
    {
        public int GroupID { get; set; }

        [Required(ErrorMessage = "Bitte geben Sie einen Gruppennamen an")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Bitte geben Sie eine kurze Beschreibung an")]
        public string Description { get; set; }

        [Required]
        public int ClubID { get; set; }
        public virtual Group Club { get; set; }

        public virtual ICollection<User> Users { get; set; }

        public virtual ICollection<GroupLeaderAssignment> GroupLeaderAssignments { get; set; }

        public virtual ICollection<Checkout> Checkouts { get; set; }

    }
}

Vereinsverwaltung/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vereinsverwaltung.Models;
using Vereinsverwaltung.Repositories;
using Vereinsverwaltung.Services;
using System.Diagnostics;
using Vereinsverwaltung.ActionFilter;

namespace Vereinsverwaltung.Controllers
{
    [GlobalAuthorizeAttribute]
    public class GroupController : Controller
    {
        private ClubContext db = new ClubContext();
        private AuthentificationService auth = new AuthentificationService();

        private IUserRepository userRepository = new UserRepository();
        private IGroupRepository groupRepository = new GroupRepository();

        //
        // GET: /Group/

        [RoleAuthorizeAttribute]
        public ActionResult Index()
        {
            int clubID = (int)ViewData["ClubId"];
            return View(this.groupRepository.getClubGroups(clubID));
        }

        //
        // GET: /Group/Details/5

        [GroupAuthorizeAttribute]
        [RoleAuthorizeAttribute]
        public ActionResult Details(int id)
        {
            Group group = this.groupRepository.GetGroupByID(id);
            return View(group);
        }

        //
        // GET: /Group/Create

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Group/Create

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        [HttpPost]
        public ActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {
                int clubID = (int)ViewData["ClubId"];

                group.ClubID = clubID;
                this.groupRepository.InsertGroup(group);
                this.groupRepository.Save();
                return RedirectToAction("Edit", new { id = group.GroupID });
            }

            return View(group);
        }
        
        //
        // GET: /Group/Edit/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Edit(int id)
        {

            Group group = this.groupRepository.GetGroupByID(id);
            if (group == null) return RedirectToAction("index");
            IEnumerable<User> clubUsers = this.userRepository.getClubUsers(group.ClubID);
            List<User> availableGroupUsers = new List<User>();

            foreach (var clubUser in clubUsers)
            {
                Boolean isInside = false;
                foreach (var groupUser in group.Users)
                {
                    if (clubUser.UserID == groupUser.UserID)
                    {
                        isInside = true;
                    }
                }
                if (!isInside)
                {
                    availableGroupUsers.Add(clubUser);
                }
            }
            ViewBag.ClubUsers = availableGroupUsers;
            return View(group);

        }

        //
        // POST: /Group/Edit/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        [HttpPost]
        public ActionResult Edit(Group group)
        {
            if (ModelState.IsValid)
            {
                this.groupRepository.UpdateGroup(group);
                this.groupRepository.Save();
                return RedirectToAction("Index");

            }
            return View(group);
        }

        //
        // GET: /Group/Delete/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Delete(int id)
        {
            Group group = this.groupRepository.GetGroupByID(id);
            return View(group);
        }

        //
        // POST: /Group/Delete/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            this.groupRepository.DeleteGroup(id);
            this.groupRepository.Save();

            return RedirectToAction("Index");
        }

        //
        // GET: /Group/5/AddUser/1

        public ActionResult AddUser(int groupid, int userid)
        {
            this.groupRepository.InsertUser(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Group/5/RemoveUser/1

        public ActionResult RemoveUser(int groupid, int userid)
        {
            this.groupRepository.RemoveLeader(groupid, userid);
            this.groupRepository.Save();
            this.groupRepository.RemoveUser(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Group/5/AddLeader/1

        public ActionResult AddLeader(int groupid, int userid)
        {
            this.groupRepository.AddLeader(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Group/5/RemoveLeader/1

        public ActionResult RemoveLeader(int groupid, int userid)
        {
            this.groupRepository.RemoveLeader(groupid, userid);
            this.groupRepository.Save();
            return Json("saved", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public int getClubID()
        {
            if (Session["clubID"] != null)
            {
                return (int)Session["clubID"];
            }
            else
            {
                int clubID = auth.getClubIdByEmail(System.Web.HttpContext.Current.User.Identity.Name);
                Session.Add("clubID", clubID);
                return clubID;
            }
        }
    }
}

Vereinsverwaltung/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vereinsverwaltung.Models;
using Vereinsverwaltung.Services;
using Vereinsverwaltung.Repositories;
using System.Web.Security;
using Vereinsverwaltung.ActionFilter;
using Vereinsverwaltung.Models.ViewModels;

namespace Vereinsverwaltung.Controllers
{
    [GlobalAuthorizeAttribute]
    public class UserController : Controller
    {

        private AuthentificationService auth = new AuthentificationService();
        private RegisterService reg = new RegisterService();
        private ClubContext db = new ClubContext();

        private IUserRepository userRepository = new UserRepository();
        private IGroupRepository groupRepository = new GroupRepository();


        //
        // GET: /User/

        [RoleAuthorizeAttribute]
        public ActionResult Index()
        {
            int clubID = (int)ViewData["ClubId"];
            ViewBag.Groups = this.groupRepository.getClubGroups(clubID);
            return View(this.userRepository.getClubUsers(clubID));
        }

        //
        // GET: /User/Search

        [RoleAuthorizeAttribute]
        public ActionResult Search()
        {
            int clubID = (int)ViewData["ClubId"];
            ViewBag.Groups = this.groupRepository.getClubGroups(clubID);
            return View(this.userRepository.getClubUsers(clubID));
        }

        //
        // GET: /User/Details/5

        [RoleAuthorizeAttribute]
        [UserAuthorizeAttribute]
        public ActionResult Details(int id)
        {
            User user = this.userRepository.GetUsertByID(id);
            return View(user);
        }

        //
        // GET: /User/Create

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter", "Gruppenleiter" })]
        public ActionResult Create()
        {
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "Name");

            List<Group> Groups =  this.groupRepository.getClubGroups((int)ViewData["ClubId"]).ToList();

            /*
            if (ViewData["Role"] != null && ViewData["Role"] == "Gruppenleiter")
            {
                // Nicht Gruppenleiter aus Groups entfernen
            }
            */

            ViewBag.GroupID = new SelectList(Groups, "GroupID", "Name");
            return View();            
        } 

        //
        // POST: /User/Create

        [HttpPost]
        [RoleAuthorizeAttribute(Role = new string[] { "Leiter", "Gruppenleiter" })]
        public ActionResult Create(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                User user = new User();
                user.FirstName = userViewModel.FirstName;
                user.LastName = userViewModel.LastName;
                user.Password = userViewModel.Password;
                user.Email = userViewModel.Email;
                user.BirthDate = userViewModel.BirthDate;
                user.RoleID = userViewModel.RoleID;

                int clubID = (int)ViewData["ClubId"];
                user.CreationDate = DateTime.Now;
                user.ClubID = clubID;
                user = reg.CreateUser(user);            

                // Check ob Benutzer user in Gruppe geben darf, fehlt!
                if (userViewModel.GroupID != 0)
                {
                    this.groupRepository.InsertUser(userViewModel.GroupID, user.UserID);
                    this.groupRepository.Save();
                }

                return RedirectToAction("Index");
            }

            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "Name", userViewModel.RoleID);
            ViewBag.GroupID = new SelectList(groupRepository.getClubGroups((int)ViewData["ClubId"]), "GroupID", "Name");
            return View(userViewModel);

        }
        
        //
        // GET: /User/Edit/5

        [UserAuthorizeAttribute]
        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Edit(int id)
        {
            if (id == null) return RedirectToAction("Index");
            User user = this.userRepository.GetUsertByID(id);
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "Name", user.RoleID);
            ViewBag.ClubID = new SelectList(db.Clubs, "ClubID", "Name", user.ClubID);
            return View(user);
            
        }

        //
        // POST: /User/Edit/5
    
        [HttpPost]
        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Edit(User user, int id)
        {
            if (ModelState.IsValid)
            {
                this.userRepository.UpdateUser(user);
                this.userRepository.Save();
                return RedirectToAction("Index");

            }
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "Name", user.RoleID);
            ViewBag.ClubID = new SelectList(db.Clubs, "ClubID", "Name", user.ClubID);
            return View(user);

            
        }

        //
        // GET: /User/Delete/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        public ActionResult Delete(int id)
        {

            User user = this.userRepository.GetUsertByID(id);
            return View(user);

            
        }

        //
        // POST: /User/Delete/5

        [RoleAuthorizeAttribute(Role = new string[] { "Leiter" })]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {

            this.userRepository.DeleteUser(id);
            this.userRepository.Save();

            return RedirectToAction("Index");
            
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Vereinsverwaltung/Views/Group/Create.cshtml
@model Vereinsverwaltung.Models.Group

@{
    ViewBag.Title = "Create";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-stacked" })) 
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Group</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="actions">
            <input type="submit" class="btn primary" value="Gruppe erstellen" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Vereinsverwaltung/Views/Group/Delete.cshtml
@model Vereinsverwaltung.Models.Group

@{
    ViewBag.Title = "Delete";
}

<div class="alert-message error fade in" data-alert="alert">
    <a class="close" href="#">×</a>
    <p><strong>Woow!</strong> Sicher das du löschen möchtest? @Html.ActionLink("Nein", "Index").</p>
</div>

<div>
    <h4>Gruppe</h4>
    <dl>
    <dt>Name</dt>
    <dd>@Html.DisplayFor(model => model.Name)</dd>
    <dt>Description</dt>
    <dd> @Html.DisplayFor(model => model.Description)</dd>
    </dl>
</div>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" class="btn danger" />
    </p>
}

Vereinsverwaltung/Views/Group/Details.cshtml
@model Vereinsverwaltung.Models.Group

@{
    ViewBag.Title = Model.Name;
}

<div>
    <h4>Gruppe</h4>
    <dl>
    <dt>Name</dt>
    <dd>@Html.DisplayFor(model => model.Name)</dd>
    <dt>Description</dt>
    <dd> @Html.DisplayFor(model => model.Description)</dd>
    <dt>Mitglieder</dt>
    <dd>
        <ul>
            
      
        @foreach (var user in Model.Users)
        {
            if (user.GroupLeaderAssignments.Count() > 0)
            {
                // In Welchen Gruppen
                foreach (var groupLeader in user.GroupLeaderAssignments)
                {
                    if (Model.GroupID == groupLeader.GroupID)
                    {
                        <li>@Html.ActionLink(user.Email + "(GruppenLeiter)", "Details", "User", new { id = user.UserID }, null)</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink(user.Email, "Details", "User", new { id = user.UserID }, null)</li>
                    }
                }
            }
            else
            {
                <li>@Html.ActionLink(user.Email, "Details", "User", new { id = user.UserID }, null)</li>
            }

        }
          </ul>
    </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GroupID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Vereinsverwaltung/Views/Group/Edit.cshtml
@model Vereinsverwaltung.Models.Group

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@{
    ViewBag.Title = Model.Name;
}


<ul class="tabs" data-tabs="tabs">
    <li class="active"><a href="#group">Gruppe</a></li>
    <li><a href="#members">Mitglieder</a></li>
</ul>
<div id="my-tab-content" class="tab-content">

    @* GROUP *@
    <div class="active tab-pane" id="group">

        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-stacked" })) 
        {
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Group</legend>

                @Html.HiddenFor(model => model.GroupID)

                <div class="clearfix">
                    @Html.LabelFor(model => model.Name)
                    <div class="input">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>

                <div class="clearfix">
                    @Html.LabelFor(model => model.Description)
                    <div class="input">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>


                <div class="actions">
                    <input type="submit" class="btn primary" value="Speichern" />
                </div>
            </fieldset>
        }
    </div>

    @* MEMBERS *@
    <div class="tab-pane tab-pane-groups" id="members">
        <div class=" left">
            <h3>Nicht zugeteilte VereinsMitglieder</h3>
            <ul id="users-sortable1" class="well group-user-list">
                @foreach (var user in ViewBag.ClubUsers)
                {
                    <li data-user-id="@user.UserID">@user.FirstName @user.LastName</li>
                }
            </ul>
       
        </div>
        <div class=" right">
             <h3>Zugeteilte GruppenMitglieder</h3>
            <ul id="users-sortable2" class="well group-user-list">
                @foreach (var user in Model.Users)
                {
                    // User ist Gruppenleiter
                    if (user.GroupLeaderAssignments.Count() > 0)
                    {
                        // In Welchen Gruppen
                        foreach (var groupLeader in user.GroupLeaderAssignments)
                        {
                            if (Model.GroupID == groupLeader.GroupID)
                            {
                                <li data-user-id="@user.UserID" class="selected">@user.FirstName @user.LastName</li>
                            }
                            else
                            {
                                <li data-user-id="@user.UserID">@user.FirstName @user.LastName</li>
                            }
                        }
                    }
                    // User ist kein Gruppenleiter
                    else
                    {
                        <li data-user-id="@user.UserID">@user.FirstName @user.LastName</li>
                    }
                }
            </ul>
            <p><i>Blau markierte Benutzer sind Gruppenleiter</i></p>
        </div>
    </div>

    <script type="text/javascript">
        var GROUPID = @Model.GroupID;
    </script>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Vereinsverwaltung/Views/Group/Index.cshtml
@model IEnumerable<Vereinsverwaltung.Models.Group>

@{
    ViewBag.Title = "Gruppen";
}


@if ((int)ViewData["Role"] == 1)
{
<p>
    @Html.ActionLink("Erstellen", "Create", "Group", new { @class = "btn primary" })
</p>
}
<table>
    <tr>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            ClubID
        </th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
         <td>
            @Html.DisplayFor(modelItem => item.ClubID)
        </td>
        <td>
            
            @if ((int)ViewData["Role"] == 1)
            {
                @Html.ActionLink("Edit", "Edit", new { id = item.GroupID }) @:|
                @Html.ActionLink("Delete", "Delete", new { id = item.GroupID }) @:|
            }
            
            @Html.ActionLink("Details", "Details", new { id = item.GroupID })
        </td>
    </tr>
}

</table>